//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectAttribute.sg {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DirectAttribute.sg.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Linq;
        ///using System.Reflection;
        ///using com.bbbirder;
        ///#if UNITY_5_3_OR_NEWER
        ///using UnityEngine.Scripting;
        ///#endif
        /// // {{cnt}}
        ///namespace BBBirder
        ///{
        ///#if UNITY_5_3_OR_NEWER
        ///    [Preserve]
        ///#endif
        ///    internal static class RetrieveModule
        ///    {
        ///#if UNITY_5_3_OR_NEWER
        ///        [Preserve]
        ///#endif
        ///        static Dictionary&lt;Type, Type[]&gt; subTypes;
        ///
        ///#if UNITY_5_3_OR_NEWER
        ///        [Preserve]
        ///#endif
        ///        static Dictionary&lt;Type, MemberInfo[]&gt; targetMembers;
        ///
        ///        static RetrieveModule( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MarkedMembers {
            get {
                return ResourceManager.GetString("MarkedMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #if UNITY_5_3_OR_NEWER
        ///using UnityEngine.Scripting;
        ///#endif
        ///
        ///namespace BBBirder
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Define on arbitrary type or member to retrieve the target directly at runtime.
        ///    /// &lt;/summary&gt;
        ///#if UNITY_5_3_OR_NEWER
        ///    [Preserve]
        ///#endif
        ///    internal partial class DirectRetrieveAttribute : Attribute
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Whether the target should be automatically preserved in build.
        ///        /// &lt;/summary&gt;
        ///        public virtual bool PreserveTarget =&gt; false;
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pre {
            get {
                return ResourceManager.GetString("Pre", resourceCulture);
            }
        }
    }
}
